### ISSUE TITLE
Reponse for preflight has invalid HTTP status code 403

### ISSUE THREAD

**Issue by manoj150283** [wso2/carbon-apimgt#1029]
Hi,

I am getting below issue with api manager 1.9.1

XMLHttpRequest cannot load https://xxxxxxxxx:8243/login/1.0.0/*. Response for preflight has invalid HTTP status code 403

My CORS configuration inside api-manager.xml is

<CORSConfiguration>

```
    <!--Configuration to enable/disable sending CORS headers from the Gateway-->
    <Enabled>true</Enabled>

    <!--The value of the Access-Control-Allow-Origin header. Default values are
        API Store addresses, which is needed for swagger to function.-->
    <Access-Control-Allow-Origin>*</Access-Control-Allow-Origin>

    <!--Configure Access-Control-Allow-Methods-->
    <Access-Control-Allow-Methods>GET,PUT,POST,DELETE,OPTIONS</Access-Control-Allow-Methods>

    <!--Configure Access-Control-Allow-Headers-->
    <Access-Control-Allow-Headers>authorization,Access-Control-Allow-Origin,Content-Type,api_key,SOAPAction</Access-Control-Allow-Headers>

</CORSConfiguration>
```

Could anyone please tell me what should be the solution for this ?

**Comment by hevayo** [comment]
Hi Manoj

Check for following
1. Does XMLHttpRequest request sent from a page loaded via http. Browsers do not allow to send https request from http page. 
2. Directly access the "https://xxxxxxxxx:8243/login/1.0.0/*" from browser and check if the endpoint has a valid certificate. 
3. In the gateway you can enable wire logs and see if it return the OPTIONS call with the CORS headers. 

Regards
Jo

**Comment by mrcssoares** [comment]
socorr

**Comment by mrcssoares** [comment]
tou com problema parecido, miajuda

**Comment by harsha89** [comment]
I'm closing th issue as @hevayo replied. Please reopen if you have it.

**Comment by gopikrisna007** [comment]
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 403.
