### ISSUE TITLE
Missing release-1.2.5 tag

### ISSUE THREAD

**Issue by joedai** [wso2/carbon-apimgt#1437]
Hi,
    Carbon-apimgt 1.2.5 was shipped with API Manager 1.9.1 release. However we found 1.2.5 was not tagged.

**Comment by chamilaadhi** [comment]
this was tagged under carbon-apimgt-v1.9.1. 
https://github.com/wso2/carbon-apimgt/blob/carbon-apimgt-v1.9.1

**Comment by joedai** [comment]
Hey @chamilaadhi 
    Got 404 when visiting that url, do I need any permission to view or is it an old url?

Thanks

**Comment by chamilaadhi** [comment]
Sorry for the mistake. Use this https://github.com/wso2/carbon-apimgt/tree/carbon-apimgt-v1.9.1
