### ISSUE TITLE
Integration with service registry

### ISSUE THREAD

**Issue by yhilem** [wso2/carbon-apimgt#2945]
Hi Team!
I want use dynamic endpoints like described at https://github.com/wso2/product-apim/issues/1194.
There is an example described here : http://stackoverflow.com/questions/20199200/wso2-dynamically-adding-an-endpoint-to-loadbalance-endpoint
For example, Eureka Client provides a dynamic list of available servers so we could balance between them.

Any help.
Thanks.

**Comment by harsha89** [comment]
Please drop a mail to dev@wso2.org mentioning your requirement.
