### ISSUE TITLE
Change Lifecycle API action parameter

### ISSUE THREAD

**Issue by malinthaprasan** [wso2/carbon-apimgt#3787]
We are giving a lifecycle state not an action for "action" parameter. "action" parameter should be a verb not a state.

POST http://localhost:9090/api/am/publisher/v1/apis/change-lifecycle?action=Published&apiId=5d88cd9a-b8d1-423d-9751-60da0031d7df HTTP/1.1
Authorization: Bearer c2d376d4-3ff1-43e2-bd42-1532f120b2d5

We should either change the parameter name or use a verb as an "action" paramter.

https://github.com/wso2/carbon-apimgt/blob/C5/components/apimgt/org.wso2.carbon.apimgt.rest.api.publisher/src/main/resources/publisher-api.yaml#L992

**Comment by malinthaprasan** [comment]
Has been changed as below:
https://192.168.8.100:9443/api/am/publisher/v1.0/apis/change-lifecycle?action=**Publish**&apiId=cf06e816-32fb-4ed5-843a-ea20dd31f33d

**Comment by npamudika** [comment]
Fixed, hence closing as per the above comment.
