### ISSUE TITLE
Create unit test for APIPublisherImpl.java class

### ISSUE THREAD

**Issue by prasa7** [wso2/carbon-apimgt#3855]
This include the task related to creating test cases for https://github.com/wso2/carbon-apimgt/blob/C5/components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/APIPublisherImpl.java

**Comment by tharikaGitHub** [comment]
This issue is resolved by PRs #3802 , #3826  and  #3842

**Comment by phocq** [comment]
Hi all.
I do not change Language in view WSO2- APIMT. Can you help me change Language in source code carbon-apimgt.
Thanks.
![1](https://cloud.githubusercontent.com/assets/28803642/26298301/fadb17b2-3f00-11e7-82e9-fa441ccb5593.png)

**Comment by uvindra** [comment]
@phocq please refer to https://docs.wso2.com/display/AM210/Adding+Internationalization+and+Localization
