### ISSUE TITLE
Creating unit test for UserAwareAPIStore.java

### ISSUE THREAD

**Issue by prasa7** [wso2/carbon-apimgt#3857]
This include the task related to creating test cases for https://github.com/wso2/carbon-apimgt/blob/C5/components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/UserAwareAPIStore.java

**Comment by tharikaGitHub** [comment]
This is resolved with PR #3802
