### ISSUE TITLE
Creating unit test for AbstractAPIManager

### ISSUE THREAD

**Issue by prasa7** [wso2/carbon-apimgt#3858]
This include the task related to creating test cases for https://github.com/wso2/carbon-apimgt/blob/C5/components/apimgt/org.wso2.carbon.apimgt.core/src/main/java/org/wso2/carbon/apimgt/core/impl/AbstractAPIManager.java

**Comment by tharikaGitHub** [comment]
This issue is resolved with PR #3882

**Comment by fazlan-nazeem** [comment]
@tharikaGitHub Shouldn't we close this'?
