### ISSUE TITLE
Add language support for client side js files

### ISSUE THREAD

**Issue by pubudu538** [wso2/carbon-apimgt#3864]
Currently, UUF does not support this and it is addressed in https://github.com/wso2/carbon-uuf/issues/160 and https://github.com/wso2/carbon-uuf/issues/166.

**Comment by harsha89** [comment]
UUF is remved hence we need to find a way in react

**Comment by npamudika** [comment]
Added with https://github.com/wso2/carbon-apimgt/pull/5583
