### ISSUE TITLE
Store application list displays first 25 applications only

### ISSUE THREAD

**Issue by chamilaadhi** [wso2/carbon-apimgt#3969]

**Comment by chamilaadhi** [comment]
when subscribing, the application list also shows only the valid applications from the first 25

**Comment by phocq** [comment]
Hi all.
I do not change Language View Add Rest API. I changed Language
in file \features\apimgt\org.wso2.carbon.apimgt.publisher.feature\src\main\resources\publisher\site\themes\wso2\templates\item-add\template.jag.
When i re-build carbon-apimgt and product-apimgt using comand mnv clean install -Dcheckstyle.skip. But
language View Add Rest AP not change.
Can you help me???
![1](https://cloud.githubusercontent.com/assets/28803642/26301681/1e10ebe8-3f0c-11e7-9cc0-5512584d33e7.png)

Thanks,

**Comment by bhathiya** [comment]
@phocq Since your issue is not related to the original issue, please create a new issue if you're still facing it.
