### ISSUE TITLE
[C5][Publisher][REST API] 200 OK response return when deleting an api with invalid api id

### ISSUE THREAD

**Issue by tmkasun** [wso2/carbon-apimgt#4278]
HTTP Status code 200 (OK) is return when performing DELETE operation on  `/api/am/publisher/v1.0/apis/{uuid}` , even with an invalid api id(UUID)

![delete_issue](https://user-images.githubusercontent.com/3313885/28017953-f03c6b44-6598-11e7-99d0-1d2ae3fd6861.png)

Sample CURL for re-producing the issue 
> curl 'https://localhost:9292/api/am/publisher/v1.0/apis/3998d80d-b63f-498e-b5bc-4df7802f0e92sample_1234' -X DELETE -H 'Pragma: no-cache' -H 'Origin: https://localhost:9292' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'Authorization: Bearer 062a9dea-7fd2-302b' -H 'Accept: application/json' -H 'Cache-Control: no-cache' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36' -H 'Cookie: WSO2_AM_TOKEN_MSF4J=-a848-9e5dc83b74c1' -H 'Connection: keep-alive' -H 'Referer: https://localhost:9292/publisher/apis' -H 'DNT: 1' --compressed --insecure

**Comment by npamudika** [comment]
Closing as this will be tracked via https://github.com/wso2/product-apim/issues/1445
