### ISSUE TITLE
[C5][Authenticator] Sending scope names in authorization code & access token requests 

### ISSUE THREAD

**Issue by npamudika** [wso2/carbon-apimgt#4298]
When requesting an authorization code or an access token, a space separated scopes list is used. 

Currently, we send the scope keys as a space separated list, but when concerning userability perspective, using scope names is preferable. But what if a scope name has a space? Hence, cannot use the scope name.

So need to come up a mapping from the IS side to display the scope names for the corresponding scope keys.

**Comment by rswijesena** [comment]
What are the usability issues that we have when sending scope keys?

**Comment by npamudika** [comment]
The issue is scope keys are less readable than scope names.
