### ISSUE TITLE
[C5][Authenticator] Getting details of an already existing DCR application

### ISSUE THREAD

**Issue by npamudika** [wso2/carbon-apimgt#4299]
Currently in APIM, when trying to get the consumer key/secret of an already existing DCR application by providing the application name, it does not return the details of the existing application.

But when we try to create a new application with an already existing name, it returns the data of the existing application.

Should be able to get the existing application details by providing the consumer key.

**Comment by rswijesena** [comment]
Good question, where you going to persist consumer key and secret? file based or in the database?
