### ISSUE TITLE
[C5][Gateway] undefined function 'execute_endpoint' error in gateway, when the published API doesn't have a sandbox endpoint

### ISSUE THREAD

**Issue by sajhak** [wso2/carbon-apimgt#4306]
If an API is created and published with only a production endpoint, following error is occurred at the gateway. This seems to be an issue in the bal file generation template, where it fails to replace the place holder 'execute_endpoint' with the correct syntax.

ballerina.lang.errors:Error, message: org/wso2/carbon/apimgt/gateway/2bde7015-6b9a-4169-83c4-97b3300f9d5a.bal:22: undefined function 'execute_endpoint'
at deployService(<native>:0)
at deployService(org/wso2/carbon/apimgt/gateway/utils/APICoreUtil.bal:230)
at apimPublisherEventListner.onMessage(org/wso2/carbon/apimgt/gateway/apimPublisherEventListner.bal:50)

**Comment by sajhak** [comment]
Figured that the reason for this issue is "EndpointExecutor.bal" is not packaged inside services.bsz
Function execute_endpoint is defined in EndpointExecutor.bal file and it needs to be packaged. As per discussion with @ruks and @sambaheerathan EndpointExecutor.bal needs to be packaged as a ballerina lib. This needs to be considered in next ballerina upgrade.

**Comment by ruks** [comment]
This is refactored and not relevant now.
