### ISSUE TITLE
Need to implement Basic Auhtnticator authntication logic

### ISSUE THREAD

**Issue by isharac** [wso2/carbon-apimgt#4323]
Need to implement authentication logic in Basic Authenticator when the username and password are provided.
We need an API from IS side to invoke and get the user authenticated.

https://github.com/wso2/carbon-apimgt/blob/master/components/apimgt/org.wso2.carbon.apimgt.rest.api.commons/src/main/java/org/wso2/carbon/apimgt/rest/api/common/impl/BasicAuthAuthenticator.java#L78

**Comment by nuwand** [comment]
We do not require Basic Authentication for the Product REST API as of now. So let's remove this class altogether. If we're implementing basic authentication it needs to be done properly taking into considerations the interactions with IS and authorizations as well.

**Comment by isharac** [comment]
+1
