### ISSUE TITLE
[C5][Store] Supporting SSO in API Store

### ISSUE THREAD

**Issue by npamudika** [wso2/carbon-apimgt#4368]
This feature enables API Store users to gain access to multiple other related applications (publisher/admin-portal), depending on the permissions, without having to repeatedly authenticate themselves when they are authenticated against one application (store).

Fixed with PRs [1] & [2].
[1] #4316 
[2] #4345

**Comment by malinthaprasan** [comment]
Closed as the PRs are merged.
