### ISSUE TITLE
[C5] Packing unwanted node_modules directory, causing large pack size

### ISSUE THREAD

**Issue by tmkasun** [wso2/carbon-apimgt#4404]
When building the product-apimgt we copy the **org.wso2.carbon.apimgt.store.feature** and **org.wso2.carbon.apimgt.publisher.feature**  features into _<PRODUCT_HOME>/wso2/lib/feature/_ without excludin the _node_modules_ directory.
**node_modules** directly should have been excluded at the first place rather than coping and removeign it afterword [\[1\]][1] .

![node_modules](https://user-images.githubusercontent.com/3313885/29177864-7f80b9e0-7e0d-11e7-90e7-9b2a2dcc6ab8.png)

\[1\] : https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/p2.inf#L3

[1]: https://github.com/wso2/carbon-apimgt/blob/master/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/p2.inf#L3

**Comment by rswijesena** [comment]
Actually, I tried to do it, However, could not find a way to exclude first place rather copying and deleting, what is your suggested solution?

**Comment by tmkasun** [comment]
@rswijesena, issue was fixed with this [PR][1]

[1]: https://github.com/wso2/product-apim/pull/1494
