### ISSUE TITLE
configuration doesn't exist for the namespace: wso2.carbon.apimgt.publisher.rest.api in deployment yaml. Hence return null object

### ISSUE THREAD

**Issue by RavinduHasithanjana** [wso2/carbon-apimgt#4496]
When logged into the publisher and api are listed the error occurs in the console 
<img width="1663" alt="screen shot 2017-09-02 at 1 40 22 am" src="https://user-images.githubusercontent.com/17488349/29986185-ea27f19a-8f7f-11e7-9d01-5565567e75a3.png">

**Comment by malinthaprasan** [comment]
Since we have moved to carbon-auth based key manager and several other component updates and fixes we should not be seeing this error now. Please recheck with the latest pack.
