### ISSUE TITLE
org.wso2.carbon.apimgt.usage.client.exception.APIMgtUsageQueryServiceClientException: Error occurred while querying from JDBC databaseInvalid object name 'API_REQUEST_SUMMARY'.	

### ISSUE THREAD

**Issue by mayoub1988** [wso2/carbon-apimgt#4567]
I got the below issue in the system logs when I requested analytics about API

 ERROR {JAGGERY.modules.statistics.usage:jag} - org.wso2.carbon.apimgt.usage.client.exception.APIMgtUsageQueryServiceClientException: Error occurred while querying from JDBC databaseInvalid object name 'API_REQUEST_SUMMARY'.

**Comment by pubudu538** [comment]
Hi,

Are you getting this exception continuously? 

This exception could occur if the stats related tables are not created in stats database. These tables are getting created at the first run of spark scripts which is periodically getting executed in the analytics server. 

Thank you!

**Comment by mayoub1988** [comment]
Hi,
Thanks for your support, but I configured all the data sources with MSSQL and executed all scripts on the database and I tested all the data sources connections and all are healthy connections, but I still getting this error

**Comment by ruks** [comment]
Hi,

Were you able to solve this issue? Didn't you see the tables created in stat db?
