### ISSUE TITLE
http 500 on publisher page and Cannot read property "apis" from null after renaming api

### ISSUE THREAD

**Issue by billtatwork** [wso2/carbon-apimgt#4629]
**Description:**
API management publisher page returns http 500 and wso2carbon.log shows following error when an api is renamed in carbon console:

TID: [-1234] [] [2017-10-09 10:13:28,094] ERROR {org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO} -  Unable to find the API: hunters-TestChanged-v1 in the database {org.wso2.carbon.apimgt.impl.dao.ApiMgtDAO}
TID: [-1234] [] [2017-10-09 10:13:28,098] ERROR {JAGGERY.site.pages.index:jag} -  org.wso2.carbon.apimgt.api.APIManagementExcept
ion: Unable to find the API: hunters-TestChanged-v1 in the database {JAGGERY.site.pages.index:jag}
TID: [-1234] [] [2017-10-09 10:13:28,102] ERROR {org.jaggeryjs.jaggery.core.manager.WebAppManager} -  org.mozilla.javascript.Ecm
aError: TypeError: Cannot read property "apis" from null (/publisher/site/blocks/listing/block.jag#40) {org.jaggeryjs.jaggery.co
re.manager.WebAppManager}
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "apis" 
from null (/publisher/site/blocks/listing/block.jag#40)
        at org.jaggeryjs.scriptengine.engine.RhinoEngine.execScript(RhinoEngine.java:571)

**Suggested Labels:**

**Affected Product Version:**
Api manager 2.1

**OS, DB, other environment details and versions:**    
Redhat Enterprise linux 7.1
java version "1.8.0_144"

**Steps to reproduce:**
Create an api in store and publish
Rename using carbon console
attempt to access publisher through web

**Comment by rswijesena** [comment]
"Rename using carbon console" It is not recommended to use carbon console to change the APIs, Use publisher instead and AFAIK, there is a no proper way to re-name an API even in the publisher.

**Comment by billtatwork** [comment]
Thanks for the feedback.  Rename of api would be a useful feature…

Bill

**Comment by praminda** [comment]
Closing the issue since answer for original issue is provided. We'll consider the requested feature, "Renaming APIs" for APIM v3
