### ISSUE TITLE
[NPM] package-lock.json files are untracked

### ISSUE THREAD

**Issue by menuka94** [wso2/carbon-apimgt#4676]
**Description:**
`package-lock.json` should be either committed or added to .gitignore depending on the requirements.

**References:**
- https://github.com/nodejs/citgm/issues/451
- https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5
- https://github.com/hapijs/contrib/issues/114

**Suggested Labels:**
question, enhancement, 3.0.0

**OS, DB, other environment details and versions:**   
NPM 5

**Comment by npamudika** [comment]
According to https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md, the package-lock.json files are intended to be checked into source control, and we cannot add them to .gitignore due to that reason. Hence closing the issue.
