### ISSUE TITLE
Threat protector for APIM Gateway

### ISSUE THREAD

**Issue by bhathiya** [wso2/carbon-apimgt#4751]
Threat protector should be able to provide protection from following threats.

- Sql injection
- Javascript injection
- Server-side include injection
- XPath Abbreviated Syntax Injection

**Comment by hasuniea** [comment]
https://docs.wso2.com/display/AM210/Regular+Expression+Threat+Protection+for+API+Gateway#21c45ebb190c4b538ca050e679bd666e

**Comment by hasuniea** [comment]
https://docs.wso2.com/display/AM210/Regular+Expression+Threat+Protection+for+API+Gateway
