### ISSUE TITLE
Application Sharing support for Multiple Groups

### ISSUE THREAD

**Issue by sambaheerathan** [wso2/carbon-apimgt#4752]
**Description:**
Improving the application sharing feature to support Multiple Groups. This feature will allow a subscriber to share his application and its existing subscriptions with users belonging to different groups.

**Features:**

- An Application and its subscriptions can be shared with multiple groups
- Users who are in shared groups can make subscription and modify existing subscriptions
- When adding an application they can enter the groups which need the application
- Shared applications shouldn't appear across different teanant

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Related Issues:**

**Comment by anuruddhal** [comment]
Doc Link : https://docs.wso2.com/display/AM2xx/Sharing+Applications+Between+Multiple+Groups
