### ISSUE TITLE
Access control support for APIM publisher

### ISSUE THREAD

**Issue by bhathiya** [wso2/carbon-apimgt#4754]
Access control, based on user roles, should be available for APIs in publisher portal. When a publisher creates an API, they should be able to allow/restrict which users can/can't access their API. This is however independent from API visibility is store.

**Comment by bhathiya** [comment]
Duplicate https://github.com/wso2/product-apim/issues/1699

**Comment by anuruddhal** [comment]
Closing due to duplicate at https://github.com/wso2/product-apim/issues/1699
