### ISSUE TITLE
Allow users to use custom headers instead of Authorization header

### ISSUE THREAD

**Issue by vlgunarathne** [wso2/carbon-apimgt#4763]
**Description:**
APIs in APIM 2.1.0 are secured with OAuth2 access tokens. In order to access an API, the consumers should generate an access token and the particular request should contain the generated token as an HTTP header.
Eg: "Authorization: Bearer NtBQkXoKElu0H1a1fQ0DWfo6IX4a"

Problems:

i) As per the current implementation of API-M 2.1.0 the structure of the access token is as above and the header field is hard coded  to be "Authorization". When the Gateway receives a request to access a resource, it looks for the access token by referring to the            header field "Authorization". The proposed implementation is to give each and every tenant in the system, the capability to have a, "per tenant" based customized authorization header field.

   Eg:
Tenant 1 : hr.lk         --> "HR_Auth : Bearer NtBQkXoKElu0H1a1fQ0DWfo6IX4a"
Tenant 2 : eng.lk      --> "ENG_Auth : Bearer NtBQkXoKElu0H1a1fQ0DWfo6IX4a"

   NB: This feature also supports the current implementation of "Authorization" as the header field, so that it doesn't affect the existing API-Ms in production.

ii) In API-M 2.1.0 there is a feature to restrict the access token, that is being sent in the request, to be passed through to the production endpoint from the Gateway. The configuration relevant to this is in the "api-manager.xml" and it is as follows;
    <RemoveOAuthHeadersFromOutMessage>true</RemoveOAuthHeadersFromOutMessage>
    If the value is set to true then the Gateway will not pass the access token to the back end and if it's false, then it will. Since this configuration resides in the "api-manager.xml", it applies in a "per server" basis. The proposal is to migrate it to the "tenant-conf.json"       so that this configuration can be applied in a "per tenant" basis.

**Suggested Labels:**
APIM 2.1.0

**Suggested Assignees:**
@vlgunarathne

**Affected Product Version:**
2.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sambaheerathan** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/4875

**Comment by Mariangela** [comment]
- **Corresponding doc JIRA**: https://wso2.org/jira/browse/DOCUMENTATION-7632

- **WSO2 Documentation:** https://docs.wso2.com/display/AM2xx/Securing+APIs

- Issue(s) that were reported that correspond to this GitHub issue.
https://github.com/wso2/product-apim/issues/2503
