### ISSUE TITLE
No indication on error while importing invalid swagger definition in API design phase

### ISSUE THREAD

**Issue by tgtshanika** [wso2/carbon-apimgt#4845]
**Description:**
When an invalid swagger definition is imported under API definition, the error message is not getting populated. Ideally, the swagger content should be validated and validation error message should be indicated to the user.

**Affected Product Version:**

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**
1. Start creating an API
2. Go to API design phase and click on Import button under API definition.
3. Provide an invalid swagger definition and click on import

**Related Issues:**

**Comment by bhathiya** [comment]
This is fixed in 2.6.0
