### ISSUE TITLE
Unnecessory error log printed when SSO is enabled for API Store

### ISSUE THREAD

**Issue by praminda** [wso2/carbon-apimgt#4850]
**Description:**
When SSO is enabled and unauthenticated user (anonymous) visits the Store api listing page, following error log is printed.
```
ERROR {org.wso2.carbon.apimgt.hostobjects.APIStoreHostObject} - Invalid types of input parameters. {org.wso2.carbon.apimgt.hostobjects.APIStoreHostObject}

ERROR {JAGGERY.site.pages.list-apis:jag}
```
This is happening due to trying to check user permissions of unauthenticated SSO session \[[1]]. 

[1]: https://github.com/wso2/carbon-apimgt/blob/6.x/features/apimgt/org.wso2.carbon.apimgt.store.feature/src/main/resources/store/site/themes/wso2/templates/sso/filter/template.jag#L41

**Affected Product Version:** 2.1.0

**Steps to reproduce:**
* Enable SSO for API Store
* Visit api listing page without logging into the store
* Check logs

**Comment by bhathiya** [comment]
Unable to reproduce in 2.2.0-SNAPSHOT pack.
