### ISSUE TITLE
Travis-CI config and build status icon issues

### ISSUE THREAD

**Issue by tmkasun** [wso2/carbon-apimgt#4861]
**Description:**

- Travis builds for 6.1.x branch fails time to time due to exceeding max log size
- Build status icon links to invalid Travis build page

![image](https://user-images.githubusercontent.com/3313885/34247176-8cabc896-e657-11e7-96a0-e01a8d8c65f0.png)

**Affected Product Version:**
- N/A

**OS, DB, other environments details and versions:**    

- N/A

**Comment by bhathiya** [comment]
This issue is not there in 6.x branch.
