### ISSUE TITLE
[Store App]Change Error Message in Forgot password page

### ISSUE THREAD

**Issue by sambaheerathan** [wso2/carbon-apimgt#4873]
**Description:**
The error message contains wso2 cloud URL hence it has to be removed.
![image](https://user-images.githubusercontent.com/1588865/34299246-f6af929a-e747-11e7-93eb-7f5f14aa7af0.png)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**
1.Go to Store sign in page
2.Click on Forget password
3.In the appearing window enter the username and click request password change.

**Related Issues:**

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/4903
