### ISSUE TITLE
Restrict api visibility restricted to publisher/creator roles at store front

### ISSUE THREAD

**Issue by chanaka3d** [wso2/carbon-apimgt#4899]
**Description:**

With the wum updated wso2am-2.1.0 ( wso2am-2.1.0.1514757889712 ) Following behavior can be observed.

I have created a tenant with following set of users and assign them roles as bellow.

**creator1**
Internal/creator
Internal/subscriber
Internal/everyone
Internal/test

**publisher1**
Internal/publisher
Internal/subscriber
Internal/everyone

**subscriber1**
Internal/subscriber
Internal/everyone

**Note:** publisher1 and creator1 were assigned with internal/subscriber role to allow them to login to the store. Additionally the creator1 has a custom role internal/test.

wso2.com tenant admin login to the publisher and create a new API ( say “PetStore” ) and publish it. While creating the “PetStore” API following configuration is set to restrict access base on the internal/test role.

![access-control0](https://user-images.githubusercontent.com/3424539/34598527-47fc2b6a-f213-11e7-9f0f-0790fca59206.png)

When the permission is set as in the above screen the creator1 ( who has Internal/test role ) is able to view the “PetStore” api after login in to publisher. But publisher1 ( who does not have internal/test role ) is not able to view the “PetStore” api after login in to publisher.

But in the store font publisher1, creator1, and subscriber1 users can view the “PetStore” after login in.

![access-control1](https://user-images.githubusercontent.com/3424539/34598548-5f1003da-f213-11e7-8d6f-e290642db39f.png)

When the permission is set as in the above screen, both publisher1, and creator1 can view the “PetStore” api even though publisher1 does not have the Internal/test role assigned. But the subscriber1 is not able to view the api.

The expected behavior is to restrict access to publisher1 in store for viewing PetStore api.

**Affected Product Version:** 
2.1.0

**Ubuntu, H2, APIM 2.1.0 - update 1514757889712**

**Comment by npamudika** [comment]
This has been fixed with https://github.com/wso2/carbon-apimgt/pull/4974
