### ISSUE TITLE
Remove unused parameters in api-manager.xml

### ISSUE THREAD

**Issue by shaniR** [wso2/carbon-apimgt#4923]
**Description:**
api-manager.xml has a property RemoveUserNameFromJWTForApplicationToken under JWT which is not used anymore. 

**Suggested Labels:**
APIM 2.2.0

**Suggested Assignees:**

**Affected Product Version:* APIM 2.1.0

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/5254
