### ISSUE TITLE
Invalid swagger definition generated with newly added path parameter.

### ISSUE THREAD

**Issue by tgtshanika** [wso2/carbon-apimgt#4952]
**Description:**
When a new path parameter is defined, a parameter definition with the following format is added to API's swagger definition and in swagger-editor, we gen indications of errors with the definition.

  parameters:
       - name: id
         in: path
         allowMultiple: false
         required: true
         type: string

**Steps to reproduce:**
* Create a new resource with a path param (/order/{id})
* Go to swagger editor and you will see the validation errors. It seems like 'allowMultiple' attribute is causing this validation errors.

**Comment by bhathiya** [comment]
`allowMultiple: false` is not there anymore. Hence not reproducible.
