### ISSUE TITLE
API Gateway is not populating/appending x-forwarded/forwarded headers. Currently APIM simply forward those headers as is. Hence what back-end receives as the x-forwarded (say x-forwarded-host) information is, that of the client, not of the API gateway.

### ISSUE THREAD

**Issue by sanjeewa-malalgoda** [wso2/carbon-apimgt#4953]
**Description:**
API Gateway is not populating/appending x-forwarded/forwarded headers. Currently APIM simply forward those headers as is. Hence what back-end receives as the x-forwarded (say x-forwarded-host) information is, that of the client, not of the API gateway. We need to discuss this across team and come to conclusion about behavior. Logging this issue for recording purpose.

**Suggested Labels:**
apim,3.0.0

**Suggested Assignees:**

**Affected Product Version:**
2.2.0

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by deepak21singh** [comment]
I am facing the same issue... please suggest
