### ISSUE TITLE
API Manager store API returns "null" values for consumer key and secret even though visible from UI.

### ISSUE THREAD

**Issue by shagihan** [wso2/carbon-apimgt#5031]
**Description:**

When using API Manager store API and get the details of an application, Even though the Consumer key and the Consumer secret is visible from the UI, in the response those are showing as NULL. Please refer the following response.

`{
               "applicationId": "bcd75a59-fe12-4d8d-b54c-2ffb32d42069",
               "name": "DefaultApplication",
               "subscriber": "dc_test",
               "throttlingTier": "Unlimited",
               "callbackUrl": null,
               "description": null,
               "status": "APPROVED",
               "groupId": null,
               "keys": [
                              {
                                             "consumerKey": null,
                                             "consumerSecret": null,
                                             "supportedGrantTypes": null,
                                             "keyState": "COMPLETED",
                                             "keyType": "PRODUCTION",
                                             "token": {
"accessToken": null,
"tokenScopes": [],
"validityTime": 0
                 	}
	}
        ]
}`

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
APIM 2.1.0

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**

Create APIM application.
Generate keys for an application.
Remove relevant access token from the IDN_OAUTH2_ACCESS_TOKEN table.
Get the details of that application using Store API.
 
**Related Issues:**

**Comment by uvindra** [comment]
Why are you doing this step?

> Remove relevant access token from the IDN_OAUTH2_ACCESS_TOKEN table.

This is a destructive action that will negatively affect the behavior of the product. It is not recommended to directly remove an active access token from the DB

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
