### ISSUE TITLE
Improve the user experience and fix usability issues of the subscription flow of the API Store

### ISSUE THREAD

**Issue by Shenavi** [wso2/carbon-apimgt#5036]
**Description:**
It was observed that the users seem to heavily struggle around key regeneration, key generation aspects of the API Store. Need to improve the usability of the Store subscription flow.

Some use cases we identified.

1. Some users subscribe to the application but are not aware keys also should be generated since it is in a separate tab. They are stuck on the api console without being able to invoke.

2) Then another place we saw users getting stuck is on the API console when their keys are expired or they have not generated keys for their applications even after subscribing. Users are confused on how to navigate to the subscriptions page. 

it would be better if we can have a link to the key generation page from the API console. Please refer the below threads for further context.

[1] Mail Thread : API Manager Store Subscription flow usability issues in apim-group@wso2.com
[2] https://wso2.org/jira/browse/APIMANAGER-5971
[3] [Hot Jar Analysis] Identified Issues status of API Cloud

**Comment by chamindias** [comment]
API Store walkthrough is there to address these kind of scenarios.
![image](https://user-images.githubusercontent.com/8359365/36580246-7b7f02a0-188d-11e8-8ccb-005034b5b960.png)

![image](https://user-images.githubusercontent.com/8359365/36580316-bffa6b90-188d-11e8-9430-ab83f2616eda.png)

Users (usually new users) will be guided to use API store properly.
