### ISSUE TITLE
Rest API for publisher - API GET returns an empty scopes Array object

### ISSUE THREAD

**Issue by chanaka3d** [wso2/carbon-apimgt#5088]
**Description:**
Rest API for publisher - API GET returns an empty scopes Array object. 

**Affected Product Version:**

7.0.104-SNAPSHOT

**Steps to reproduce:**

Do a get request to get API parsing the api uuid

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
