### ISSUE TITLE
On a multi-tenant deployment, when you login to the Store, you're redirected to the store listing page instead of the api listing page.

### ISSUE THREAD

**Issue by nuwand** [wso2/carbon-apimgt#5191]
On a setup that has more than 1 tenant, the default /store url path displays a listing of all tenant stores. After you click on the store you belong to and click on sign in and login, you should be presented with the Store Home page which lists all APIs. But the current behavior is such that you're redirected to the store listing page. You need to click the relevant Store again (second time) to see the APIs.

**Comment by bhathiya** [comment]
Not reproducible in 2.5.0
