### ISSUE TITLE
MacOS default unarchiver tool is unable to extract the SDK zip

### ISSUE THREAD

**Issue by nuwand** [wso2/carbon-apimgt#5192]
The API Store allows you to download SDKs of APIs. These are downloaded in the form of zip files. On MacOS, the default unarchiver tool and winzip both fail to extract these files. These can be extracted using the 'unzip' command on the command line (Terminal) though. The Terminal gives the following warning when extracting.

> 1 extra byte at beginning or within zipfile (attempting to process anyway)

**Comment by isharac** [comment]
I’m closing this issue because it has been inactive for more than two years. Please reopen if you still encounter this issue with the latest version.
