### ISSUE TITLE
Downloading Server Side SDK does not work

### ISSUE THREAD

**Issue by nuwand** [wso2/carbon-apimgt#5194]
On the publisher, when you open up the Swagger Editor by clicking on the "Edit Source" button which appears near the Resource Section, there are options to download Client SDKs and Server SDKs. While Client SDKs download just fine, Server SDK downloads fail. The reason is because the Swagger editor seems to be sending a request to an "http" URL while the application (publisher) is being accessed over "https". The web browser (Firefox, Chrome) prevents this request and issues an error on the developer console saying "Blocked loading mixed active content"

**Comment by tgtshanika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5259/files
