### ISSUE TITLE
API Developers with 'publisher' only permission cannot manage Subscriptions

### ISSUE THREAD

**Issue by nuwand** [wso2/carbon-apimgt#5206]
API Developers with 'publisher' role are the only ones capable of setting up subscriptions options such as subscription availability across tenants. However its the 'creator' role which can manage subscriptions on the Publisher webapp. This doesn't feel right. Need to allow managing subscriptions to the 'publisher' users as well

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/5467
