### ISSUE TITLE
The incorrect steps provided in 'Customize+the+API+Store+and+Gateway+URLs+for+Tenants' has to fixed

### ISSUE THREAD

**Issue by tgtshanika** [wso2/carbon-apimgt#5208]
**Description:**
In [1], following steps has to be corrected.

**Setup custom domain mapping in the registry**
Step 1 : Log in to the management console as (https://<HostName>:9443/carbon) as admin (or tenant admin).
Correct step:  
Log in to the management console as (https://<HostName>:9443/carbon) as the super admin

Step 3: The directory path has to be corrected as followd
 **customurl/api-cloud/<tenant-domain>/urlMapping/**
Need to change the screenshots accordingly

Step 4: The navigation URL has to be corrected as follows
**customurl/api-cloud/<tenant-domain>/urlMapping/**

The creating resource name should be named with tenant domain name (ie :wso2.com). Need to update the screenshot accordingly. 

Improvements:
Better to add a screenshots of publisher and store to show how the config change affects the store url and gateway urls.

[1] https://docs.wso2.com/display/AM2xx/Customize+the+API+Store+and+Gateway+URLs+for+Tenants

**Comment by taniamahanama** [comment]
Fixed
