### ISSUE TITLE
Publisher UI doesn't read the parameters with "$ref" when importing a Swagger file

### ISSUE THREAD

**Issue by iloshinik** [wso2/carbon-apimgt#5517]
**Description:**
When importing a swagger file (.json / .yaml), the Publisher UI is unable to read the parameters with the reference definition, "$ref", hence the parameters list including Parameter Name, Description, Parameter Type, etc. is empty. But, these parameters are available in the API Store under the related resource once the API is published.

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
wso2am-2.2.0

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**
1. Create an API in wso2am-2.2.0 using a Swagger file (.json / .yaml).
2. Check the parameters list of the available resources.

**Related Issues:**

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/commit/1b23e29e1818cae840b6b33594a70dc37e6386bc
