### ISSUE TITLE
Wrongly calculated x5t header in JWT

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/carbon-apimgt#5535]
**Description:**
x5t header variable contains in the generated JWT assertion  is wrongly calculated. Thumbprint should be calculated as foolows.
1. DER encoding
2. SHA-1 digest
3. Hexify
--> Thumbprint
4. Base64-url encoding
-->x5t header

In APIM 2.1.0 step 3 (hexifying) is missing. Therefore , the generated x5t is invalid.

**Suggested Labels:**
Bug

**Affected Product Version:**
2.1.0

**Steps to reproduce:**
1. Enable JWT generation in api-manager.xml file
2. Enable wire logs in log4j.properties file.
3. Deploy sample API and invoke.
4. Copy the X-JWT-Assertion header in the wire logs.
5. Decode and observe x5t header as **a_jhNus21KVuoFx65LmkW2O_l10**, This should be **NmJmOGUxMzZlYjM2ZDRhNTZlYTA1YzdhZTRiOWE0NWI2M2JmOTc1ZA** for the default certificate.

**Comment by gusto2** [comment]
Apparently with the new compuation, external libraries (jose, jwt.io) consider the signature as invalid
 https://stackoverflow.com/questions/53611059/wso2am-2-6-0-invalid-jwt-signature
