### ISSUE TITLE
Synapse global timeout is greater than socket timeout value

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/carbon-apimgt#5560]
**Description:**
API Manager 2.2.0 (older versions as well) has a default socket timeout value of **60000ms** whereas the default synapse global timeout defined in the **synapse.properties** file being **120000ms**. This is useless as socket timeout will be triggered in 60 seconds anyway, despite having a larger synapse timeout. 
Should fix as per below,
`socket timeout > synapse global timeout`

**Affected Product Version:**
2.2.0

**Comment by bhathiya** [comment]
Fixed by https://github.com/wso2/product-apim/pull/3655
