### ISSUE TITLE
REST API support for dynamic SSL certificate configuration feature

### ISSUE THREAD

**Issue by nipunthathsara** [wso2/carbon-apimgt#5569]
**Description:**
Current implementation of API Manager 2.1.0 REST APIs do not support for Dynamic SSL certificate configuration feature available in Publisher. This could be able to done via REST apis as well.

**Affected Product Version:**
2.1.0

**Comment by menakaj** [comment]
The REST api is provided for the Dynamic SSL Certificate Installation feature. https://github.com/wso2/carbon-apimgt/pull/5615. 

This issue can be closed.

**Comment by npamudika** [comment]
Closing as per the above comment.
