### ISSUE TITLE
Logout request destination not matching with identityProviderLogoutURL

### ISSUE THREAD

**Issue by Dumindu-Kanchana** [wso2/carbon-apimgt#5571]
**Description:**

In the setup, SAML SSO for store/publisher (APIM 2.2.0) with an external IDP (PingID) without federating via IS is configured. But the logout is failing due to an issue in the logout request.

identityProviderURL" : "https://abc.com/idp/SSO.saml2",
identityProviderLogoutURL" : "https://bcd.com/idp/SLO.saml2"

So the logout request is being sent to the correct identityProviderLogoutURL configured above. But the Destination attribute in the SAML LogoutRequest contains the identityProviderURL which leads to a validation failure in the PingID side due to URL mismatch. 

**Suggested Labels:**

APIM 2.2.0

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5576
