### ISSUE TITLE
 No validation for revokeTokensOfUserByAppResponse operation of APIKeyMgtSubscriberService 

### ISSUE THREAD

**Issue by dushaniw** [wso2/carbon-apimgt#5573]
**Description:**
APIKeyMgtSubscriberService admin service of APIM has the revokeTokensOfUserByAppResponse operation to revoke tokens of given user for given application.
Existing implementation does not validate the service based on the logged in user. If multiple applications exist with the same application name, and whoever the logged in user is, the service operation will revoke the tokens of given user for all the applications in the AM_APPLICATION table.

**Suggested Labels:**
Bug

**Suggested Assignees:**

**Affected Product Version:**
API-M-2.2.0

**OS, DB, other environments details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Create two applications for two sperate users (in the same tenant) with the same application name. Generate tokens for one user for both applications.  Invoke the service operation by giving any valid user credentials and application name given above and username for whom the keys were generated before.

**Comment by tharikaGitHub** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/5576
