### ISSUE TITLE
Cannot signup to API manager 

### ISSUE THREAD

**Issue by nalakas** [wso2/carbon-apimgt#5600]
**Description:**
unable to signup to API manager. the error given is 500.
[ApiSignupissue.txt](https://github.com/wso2/carbon-apimgt/files/2301684/ApiSignupissue.txt)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2am-2.6.0-alpha2-SNAPSHOT

**OS, DB, other environments details and versions:**    
OS:mac os high sierra
DB: h2 database

**Steps to reproduce:**
1.published api as a admin. 
2.try to sign as a admin.
3.try to signup

**Related Issues:**

**Comment by praminda** [comment]
@nalakas  
Please fill in following sections.

**Affected Product Version:
OS, DB, other environments details and versions:
Steps to reproduce:**

**Comment by praminda** [comment]
Duplicate of wso2/product-apim#3623
