### ISSUE TITLE
NPE occured in Soap to Rest API Creating Implement Tab

### ISSUE THREAD

**Issue by tharindu1st** [wso2/carbon-apimgt#5610]
**Description:**
# 

1. Create API
2. Select **I have a SOAP Endpoint** and give wsdl url then Select **Generate REST APIs**
3. Go through Design Tab and Select Next and Implement

Note:
This need to be done on Registry mounted Deployment.

**Comment by bhathiya** [comment]
Duplicate https://github.com/wso2/product-apim/issues/3686
