### ISSUE TITLE
authorizationUrl in swagger of store

### ISSUE THREAD

**Issue by nipun-sachintha** [wso2/carbon-apimgt#5688]
**Description:**
Multiple API Gateway environments can be configured in wso2 API manager that publish to single API store. The gateway environments we add in publisher will be visible in the drop-down list in API console in API store. When we select any gateway from that list then we analyze generated swagger, we could identify authorization URL in security definitions is pointed to the same default URL. It would not change with selection of gateways in publisher.

**Suggested Labels:**
Apim-2.1.0

**Steps to reproduce:**
Configure 3 gateways and one store in the system.
Select relevant gateways from apim publisher in the store node.
Log into apim store and select an gateway from the drop-down list in "On Environment".
Generate swagger
Then it pointed to same authorized URL
(Authourized url mentioned under security definitions)

**Comment by tgtshanika** [comment]
Fixed
