### ISSUE TITLE
JWT tokens are not generated for apps with semi-manual client registration

### ISSUE THREAD

**Issue by bhathiya** [wso2/carbon-apimgt#5732]
**Description:**
JWT tokens are not generated for apps with semi-manual client registration

**Affected Product Version:**
2.6.0

**Steps to reproduce:**
- Create an app with JWT type
- Enable `mapExistingAuthApps` in the store site.json
- Create an SP and map keys to the app.
- Generate a token.  

The generated token must be a JWT, but it is an OAuth one. 

![image](https://user-images.githubusercontent.com/3960742/45612674-60a87380-ba81-11e8-9b35-2157e83cb342.png)

**Comment by HiranyaKavishani** [comment]
When provisioning an existing OAuth client (which created outside the API Store) into the WSO2 APIM, It generates a token based on the **Token Issuer** Configuration of the OAuth client at the SP.

<img width="533" alt="image1" src="https://user-images.githubusercontent.com/29066805/57223560-20076580-7024-11e9-81ce-954a3d92bd9b.png">


There are three types of token issuers and tokens are generated according to that type.

1. **JWT** 
JWT tokens are generated for apps. 

2. **Default** 
OAuth tokens are generated for apps.

3. **org.wso2.carbon.apimgt.keymgt.issuers.APIMTokenIssuer** 
 Tokens are generated according to the token type defined at the application in APIM

<img width="614" alt="image2" src="https://user-images.githubusercontent.com/29066805/57223903-42e64980-7025-11e9-815c-f73a2af79a22.png">

Doc[1] specified about this feature and it should be clearly mentioned token type as an optional comment under step 4.

https://docs.wso2.com/display/AM260/Provisioning+Out-of-Band+OAuth+Clients
