### ISSUE TITLE
building 

### ISSUE THREAD

**Issue by ypsliu** [wso2/carbon-apimgt#5864]
hi all 👍 
  I made an error while building the project ,Can you help me

error is 
WSO2 Carbon - API Publisher Feature failure 
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (npm run build (compile)) on project org.wso2.carbon.apimgt.publisher.feature: Command execution failed.: Process exited with an error: 2 (Exit value: 2) -> [Help 1]

0 info it worked if it ends with ok
1 verbose cli [ '/software/node-v10.13.0-linux-x64/bin/node',
1 verbose cli   '/software/node-v10.13.0-linux-x64/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:prod' ]
2 info using npm@6.4.1
3 info using node@v10.13.0
4 verbose run-script [ 'prebuild:prod', 'build:prod', 'postbuild:prod' ]
5 info lifecycle wso2_apim_publisher@3.0.0~prebuild:prod: wso2_apim_publisher@3.0.0
6 info lifecycle wso2_apim_publisher@3.0.0~build:prod: wso2_apim_publisher@3.0.0
7 verbose lifecycle wso2_apim_publisher@3.0.0~build:prod: unsafe-perm in lifecycle true
8 verbose lifecycle wso2_apim_publisher@3.0.0~build:prod: PATH: /software/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/workerspace/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/software/jdk1.8.0_191/bin:/software/apache-maven-3.5.4/bin:/software/node-v10.13.0-linux-x64/bin
9 verbose lifecycle wso2_apim_publisher@3.0.0~build:prod: CWD: /workerspace/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher
10 silly lifecycle wso2_apim_publisher@3.0.0~build:prod: Args: [ '-c',
10 silly lifecycle   'NODE_ENV=production NODE_OPTIONS=--max_old_space_size=4096 webpack -p --display errors-only --hide-modules' ]
11 silly lifecycle wso2_apim_publisher@3.0.0~build:prod: Returned: code: 2  signal: null
12 info lifecycle wso2_apim_publisher@3.0.0~build:prod: Failed to exec build:prod script
13 verbose stack Error: wso2_apim_publisher@3.0.0 build:prod: `NODE_ENV=production NODE_OPTIONS=--max_old_space_size=4096 webpack -p --display errors-only --hide-modules`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/software/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/software/node-v10.13.0-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid wso2_apim_publisher@3.0.0
15 verbose cwd /workerspace/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher
16 verbose Linux 4.9.125-linuxkit
17 verbose argv "/software/node-v10.13.0-linux-x64/bin/node" "/software/node-v10.13.0-linux-x64/bin/npm" "run" "build:prod"
18 verbose node v10.13.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 2
22 error wso2_apim_publisher@3.0.0 build:prod: `NODE_ENV=production NODE_OPTIONS=--max_old_space_size=4096 webpack -p --display errors-only --hide-modules`
22 error Exit status 2
23 error Failed at the wso2_apim_publisher@3.0.0 build:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

thanks

**Comment by tmkasun** [comment]
Hi @ypsliu ,

Sorry about the delay in response, It seems you have tried to build the master branch. This branch requires to have NodeJs and NPM installed in your computer.
It seems you have required NPM and Node versions installed

> 2 info using npm@6.4.1
> 3 info using node@v10.13.0

This error `20 error code ELIFECYCLE` could be due to stale npm cache in your local repo.
Can you try below command to clean the npm cache from the Publisher ReactJs app location,

`npm cache clean --force` or `npm run clean`

> /workerspace/carbon-apimgt/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher

and try to build the carbon-apimgt repo again.

Thanks
@tmkasun

**Comment by npamudika** [comment]
Answered, hence closing the issue.
