### ISSUE TITLE
Generated backend JWT token is not validable by 3rd party tools (jwt.io, jose, ..)

### ISSUE THREAD

**Issue by gusto2** [wso2/carbon-apimgt#5884]
**Description:**

Generated backend JWT token is not validable by 3rd party tools (jwt.io, jose, ..)

**Affected Product Version:**

wso2am-2.6.0

**Steps to reproduce:**

 - enable EnableJWTGeneration
 - invoke a service with the JWT token 
 - validate the token ( using jwt.io) - the signature is not considered valid
 - validate the token using jose and VerificationKeyResolver (finding certificate based on x5t header) - the x5t header is considered invalid

**Related Issues:**

 -  Issue https://github.com/wso2/carbon-apimgt/issues/5535 effectively breaks usage of x5t, the hexify is IMHO incorrectly understood thumbprint (there is no reason to encode already encoded value) and 3rd party tools (jwt.io, jose) will not recognize it

**Comment by dinusha92** [comment]
Closing as it has been fixed with https://github.com/wso2/carbon-apimgt/pull/5963
