### ISSUE TITLE
Add Markdown support when adding docs in the publisher

### ISSUE THREAD

**Issue by Varuni-Punchihewa** [wso2/carbon-apimgt#5985]
**Description:**
Currently, when you are adding a new document to the API in the publisher, you can only give Inline, URL and File as the source type. It doesn't have a mechanism to add markdown (md) docs. 

**Suggested Labels:**
Type/Improvement

**Affected Product Version:**
APIM 2.x   

**Suggested Approach:**
- Introduce a new source type as "Markdown" in the Docs tab of the Publisher
- Once the user selects the Markdown radio button, adds a new doc, and clicks the Edit Content button, it redirects the user to a Markdown editor.
- Use a library to convert the markdown to markup language when viewing it on the Store

**Comment by npamudika** [comment]
Closing as this is available in APIM 3.0.0 now.
