### ISSUE TITLE
JWT Authentication for APIM Gateway

### ISSUE THREAD

**Issue by yhilem** [wso2/carbon-apimgt#5987]
Provide authentication for APIM Gateway with JWT tokens.
Same as https://github.com/wso2/product-apim/issues/3868

Thanks
Youcef HILEM

**Comment by yhilem** [comment]
Hi,
Implemented in 3.0.0 : https://github.com/wso2/product-apim/issues/5115
How to backport to 2.6 ?
Thanks Youcef HILEM

**Comment by tharindu1st** [comment]
Hi 
@yhilem  This was a new feature addition to 3.0.0, Therefore this will not be able to port into 2.6.0 version
