### ISSUE TITLE
API Manager is throwing error after when approval tasks are paginated.

### ISSUE THREAD

**Issue by selakap** [wso2/carbon-apimgt#6034]
**Description:**
Paginated tasks in the subscription approval section in the admin portal ( more than 1 page with approval requests) and then complete all the approval from page 2 it gives an error saying,
"The page cannot be displayed."

**Affected Product Version:**
APIM 2.1.0

**Steps to reproduce:**
- Paginated tasks in the subscription approval section in the admin portal ( more than 1 page with approval requests)
- complete all the approval from page 2
- Observe the error saying,
"The page cannot be displayed."

**Comment by npamudika** [comment]
Fixed with https://github.com/wso2/carbon-apimgt/pull/6036
