### ISSUE TITLE
Code which processes swagger and generates definitions

### ISSUE THREAD

**Issue by deostroll** [wso2/carbon-apimgt#6146]
Hi,

In the publisher we can add an existing api. We can give a swagger file or a URL to one such file...and consequently we are presented with a UI of definitions, operations, etc...

I am interested in reviewing the code for the same. Hoping someone can point me there...

Also, is there a framework or technology in here I should know beforehand that would help me understand the code faster?

**Comment by menakaj** [comment]
Thank you very much for your interest in the WSO2 API Manager.

Please refer the api-design.js file [1], which generates the resources from the swagger file.

[1] https://github.com/wso2/carbon-apimgt/blob/6.x/features/apimgt/org.wso2.carbon.apimgt.publisher.feature/src/main/resources/publisher/site/themes/wso2/templates/item-design/js/api-design.js

**Comment by menakaj** [comment]
Answered hence closing.
