### ISSUE TITLE
JWT formatter issue when adding custom application attributes

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/carbon-apimgt#6297]
**Description:**
When adding custom attributes to an application, JWT generator cannot retrieve the JSON object values.

**Affected Product Version:**
2.6.0

**Steps to reproduce:**
1. Enable and configure multiple custom attributes in an application
2. Enable and configure the JWT implementation
3. Create an application adding custom attributes.
4. Subscribe to API and Invoke
5. Decode the JWT token which shown in the server log.

**Comment by npamudika** [comment]
Fixed by https://github.com/wso2/carbon-apimgt/pull/6305
