### ISSUE TITLE
Support for export and export application with consumer keys and secrets

### ISSUE THREAD

**Issue by harsha89** [wso2/carbon-apimgt#6707]

**Comment by harsha89** [comment]
https://github.com/wso2/carbon-apimgt/pull/6635
https://github.com/wso2/carbon-apimgt/pull/6691

**Comment by ruwiniwj** [comment]
https://github.com/wso2-support/carbon-apimgt/pull/1551

**Comment by chamindias** [comment]
Please see : https://github.com/wso2/product-apim/issues/6453
