### ISSUE TITLE
Maven Build failing

### ISSUE THREAD

**Issue by shaliniatwork** [wso2/carbon-apimgt#6850]
Hi , 
The current maven build fails with the below error. Are there anything I'm missing. Please help. 

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
8.1:compile (default-compile) on project org.wso2.carbon.apimgt.rest.api.store.v
1: Compilation failure: Compilation failure:
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1
/impl/ApisApiServiceImpl.java:[63,8] duplicate class: org.wso2.carbon.apimgt.res
t.api.store.v1.impl.ApisApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/TagsApiServiceImpl.java:[20,8] duplicate class: org.wso2.carbon.apimgt.rest
.api.store.v1.impl.TagsApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/ApiProductsApiServiceImpl.java:[28,8] duplicate class: org.wso2.carbon.apim
gt.rest.api.store.v1.impl.ApiProductsApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1
/impl/SearchApiServiceImpl.java:[46,8] duplicate class: org.wso2.carbon.apimgt.r
est.api.store.v1.impl.SearchApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/SubscriptionsApiServiceImpl.java:[23,8] duplicate class: org.wso2.carbon.ap
imgt.rest.api.store.v1.impl.SubscriptionsApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/SettingsApiServiceImpl.java:[21,8] duplicate class: org.wso2.carbon.apimgt.
rest.api.store.v1.impl.SettingsApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/ApplicationsApiServiceImpl.java:[30,8] duplicate class: org.wso2.carbon.api
mgt.rest.api.store.v1.impl.ApplicationsApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/ImportApiServiceImpl.java:[21,8] duplicate class: org.wso2.carbon.apimgt.re
st.api.store.v1.impl.ImportApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/ExportApiServiceImpl.java:[20,8] duplicate class: org.wso2.carbon.apimgt.re
st.api.store.v1.impl.ExportApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1
/impl/ThrottlingPoliciesApiServiceImpl.java:[30,8] duplicate class: org.wso2.car
bon.apimgt.rest.api.store.v1.impl.ThrottlingPoliciesApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/SelfSignupApiServiceImpl.java:[21,8] duplicate class: org.wso2.carbon.apimg
t.rest.api.store.v1.impl.SelfSignupApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/gen/java/org/wso2/carbon/apimgt/rest/api/store/imp
l/v1/TenantsApiServiceImpl.java:[19,8] duplicate class: org.wso2.carbon.apimgt.r
est.api.store.v1.impl.TenantsApiServiceImpl
[ERROR] /D:/projects/wso2/carbon-apimgt-master/components/apimgt/org.wso2.carbon
.apimgt.rest.api.store.v1/src/main/java/org/wso2/carbon/apimgt/rest/api/store/v1
/impl/SdkGenApiServiceImpl.java:[34,8] duplicate class: org.wso2.carbon.apimgt.r
est.api.store.v1.impl.SdkGenApiServiceImpl

**Comment by nausicaaconsulting** [comment]
Same issue here, any idea ?
