### ISSUE TITLE
Operations have not been propagated to backend when creating graphql API

### ISSUE THREAD

**Issue by HiranyaKavishani** [wso2/carbon-apimgt#6998]
1. Import Graphql schema
2. Create graphql API
3. open console tab and look at additional properties
4. operations are getting null

**Comment by ruks** [comment]
![image](https://user-images.githubusercontent.com/1345278/64685931-73dbfc80-d4a5-11e9-840c-37f20fa5e71f.png)

Please find the attached screen shot.

**Comment by HiranyaKavishani** [comment]
Fixed in 3.0.0-m35
