### ISSUE TITLE
Readme should document what this repo about and how it's related to product-apim

### ISSUE THREAD

**Issue by chintana-zz** [wso2/carbon-apimgt#7826]
Readme file on this repo should document,
1. What this repo is about, what's the component structure etc...
2. How it's related to product-apim
3. What's the significance of it when it comes to building it from source

Right now it's very hard for a new developer to look at this repo and figure out the relationship/importance

**Comment by Camille0183** [comment]
Camille0183:patch-1components/apimgt/org.wso2.carbon.apimgt.api/src/main/java/org/wso2/carbon/apimgt/api/model/Monetization.java..usagwSkip to main content
GitHub Docs
Managing code review settings for your team
In this article
About code review settings
About team notifications
About auto assignment
Configuring team notifications
Configuring auto assignment
Disabling auto assignment
You can decrease noise for your team by limiting notifications when your team is requested to review a pull request.

Who can use this feature
Team maintainers and organization owners can configure code review settings.

Code review settings are available in all public repositories owned by an organization, and all private repositories owned by organizations on GitHub Team, GitHub Enterprise Server 2.20+, and GitHub Enterprise Cloud. For more information, see "GitHub's products."

About code review settings
To reduce noise for your team and clarify individual responsibility for pull request reviews, you can configure code review settings.

Team notifications
Auto assignment
About team notifications
When you choose to only notify requested team members, you disable sending notifications to the entire team when the team is requested to review a pull request if a specific member of that team is also requested for review. This is especially useful when a repository is configured with teams as code owners, but contributors to the repository often know a specific individual that would be the correct reviewer for their pull request. For more information, see "About code owners."

About auto assignment
When you enable auto assignment, any time your team has been requested to review a pull request, the team is removed as a reviewer and a specified subset of team members are assigned in the team's place. Code review assignments allow you to decide whether the whole team or just a subset of team members are notified when a team is requested for review.

When code owners are automatically requested for review, the team is still removed and replaced with individuals unless a branch protection rule is configured to require review from code owners. If such a branch protection rule is in place, the team request cannot be removed and so the individual request will appear in addition.

Routing algorithms
Code review assignments automatically choose and assign reviewers based on one of two possible algorithms.

The round robin algorithm chooses reviewers based on who's received the least recent review request, focusing on alternating between all members of the team regardless of the number of outstanding reviews they currently have.

The load balance algorithm chooses reviewers based on each member's total number of recent review requests and considers the number of outstanding reviews for each member. The load balance algorithm tries to ensure that each team member reviews an equal number of pull requests in any 30 day period.

Any team members that have set their status to "Busy" will not be selected for review. If all team members are busy, the pull request will remain assigned to the team itself. For more information about user statuses, see "Setting a status."

Configuring team notifications
In the top right corner of GitHub.com, click your profile photo, then click Your organizations.
Your organizations in the profile menu

Click the name of your organization.
Organization name in list of organizations

Under your organization name, click  Teams.

Teams tab

On the Teams tab, click the name of the team.
List of the organization's teams

At the top of the team page, click  Settings.
Team settings tab

In the left sidebar, click  Code review.

Select Only notify requested team members.
Code review team notifications

Click Save changes.

Configuring auto assignment
In the top right corner of GitHub.com, click your profile photo, then click Your organizations.
Your organizations in the profile menu

Click the name of your organization.
Organization name in list of organizations

Under your organization name, click  Teams.

Teams tab

On the Teams tab, click the name of the team.
List of the organization's teams

At the top of the team page, click  Settings.
Team settings tab

In the left sidebar, click  Code review.

Select Enable auto assignment.
Auto-assignment button

Under "How many team members should be assigned to review?", use the drop-down menu and choose a number of reviewers to be assigned to each pull request.
Number of reviewers dropdown

Under "Routing algorithm", use the drop-down menu and choose which algorithm you'd like to use. For more information, see "Routing algorithms."
Routing algorithm dropdown

Optionally, to always skip certain members of the team, select Never assign certain team members. Then, select one or more team members you'd like to always skip.
Never assign certain team members checkbox and dropdown

Optionally, to include members of child teams as potential reviewers when assigning requests, select Child team members.

Optionally, to count any members whose review has already been requested against the total number of members to assign, select Count existing requests.

Optionally, to remove the review request from the team when assigning team members, select Team review request.

Click Save changes.

Disabling auto assignment
In the top right corner of GitHub.com, click your profile photo, then click Your organizations.
Your organizations in the profile menu

Click the name of your organization.
Organization name in list of organizations

Under your organization name, click  Teams.

Teams tab

On the Teams tab, click the name of the team.
List of the organization's teams

At the top of the team page, click  Settings.
Team settings tab

Select Enable auto assignment to remove the checkmark.
Code review assignment button

Click Save changes.

Did this doc help you?

Privacy policy
Help us make these docs great!
All GitHub docs are open source. See something that's wrong or unclear? Submit a pull request.

Or, learn how to contribute.

Still need help?
Ask the GitHub community
Contact support
© 2023 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
Developer API
Training
Blog
About

cd52bb59d533635aeda70f65795786f4b2e821c1
