### ISSUE TITLE
Some commented configs in deployment.toml related to analytics is incorrect

### ISSUE THREAD

**Issue by TanyaM** [wso2/carbon-apimgt#7841]
deployment.toml file has following configs under [apim.analytics] which doesn't have any respective elements in the j2
```
#username = "$ref{super_admin.username}"
#password = "$ref{super_admin.password}"
```

And commented configs for 
- receiver_username
- receiver_password
- store_api_username
- store_api_password

are missing in the toml file.

**Comment by TanyaM** [comment]
Seems username and password inherits username and password of API-M node and assigned to Analytics node. 

I have updated the doc [1] with that information.
@ruks : Please check.

[1] https://apim.docs.wso2.com/en/latest/Learn/Analytics/configuring-apim-analytics/#step-3-configure-wso2-api-manager-to-publish-statistics

**Comment by ruks** [comment]
@TanyaM Tested the credentials for analytics and all are valid.
