### ISSUE TITLE
How can i make install bundle from source code of api manager product?

### ISSUE THREAD

**Issue by AndreasRusjaev** [wso2/carbon-apimgt#7853]
Hello everybody
i have seen on the page:
https://wso2.github.io/github-repositories.html.
The product product-apim consists of two repositories:
1) carbon-apimgt
2) product-apim

How can i integrate carbon-apimgt build in product-apim if i want to make an installation bundle from source code?
Thanks and best regards

**Comment by menakaj** [comment]
After building the carbon-apimgt repository, change the <carbon.apimgt.version></carbon.apimgt.version> in product-apim/pom.xml with the version of the carbon-apimgt/pom.xml file and build the product-apim repo.
