### ISSUE TITLE
[Publisher] Selected mediation policy is not preserved properly in Runtime Configurations.

### ISSUE THREAD

**Issue by dulithsenanayake** [wso2/carbon-apimgt#7941]
![Screenshot from 2019-11-26 16-39-06](https://user-images.githubusercontent.com/31464477/69630689-2e29db80-1073-11ea-9fc8-c733902b26a5.png)
![Screenshot from 2019-11-26 16-39-26](https://user-images.githubusercontent.com/31464477/69630715-33872600-1073-11ea-9d7e-d516d1552559.png)
![Screenshot from 2019-11-26 16-39-30](https://user-images.githubusercontent.com/31464477/69630726-35e98000-1073-11ea-9991-3ebeeb8d445a.png)
**Issue**
When we edit Message Mediation in Runtime Configuartions,if we select one mediation policy from global mediation and after clicking select button, if we switched from custom mediation to global mediation or none to global mediation, selected mediation policy is not preserved properly.

**Comment by tharindu1st** [comment]
This was expected since this forms need to reset between options
