### ISSUE TITLE
Error while creating a Advanced throttling tier 

### ISSUE THREAD

**Issue by Prabhashi** [wso2/carbon-apimgt#7944]
**Steps to reproduce the issue:**
1. Download a fresh WSO2 APIM 2.0.0 PACK.
2. Add the below patches to <APIM_Home>/repository/components/patches directory.

patch0610 patch0665 patch0721 patch0765 patch1243 patch2202 patch3810 patch4107 patch4173 patch4354 patch4649 patch00052 patch0630 patch0666 patch0744 patch0830 patch1343 patch2357 patch3870 patch4152 patch4246 patch4387 patch4723
patch0588 patch0653 patch0720 patch0759 patch1145 patch1999 patch2389 patch4074 patch4158 patch4353 patch4558 patch5246

3. Start the server.
4. Go to the Admin portal and add an advanced throttling tier and save it.

On the UI, it does not show any errors but when checking the logs in the terminal, below exception can be seen.

`ERROR - EventProcessorDeployer Execution plan is not deployed and in inactive state : carbon.super_resource_NewAdvancedThrottlingPolicy_default.siddhiql
org.wso2.carbon.event.processor.core.exception.ExecutionPlanConfigurationException: Cannot find attribute type as 'null' does not exist in 'RequestStream'; StreamDefinition{id='RequestStream', attributeList=[Attribute{id='messageID', type=STRING}, Attribute{id='appKey', type=STRING}, Attribute{id='appTier', type=STRING}, Attribute{id='subscriptionKey', type=STRING}, Attribute{id='apiKey', type=STRING}, Attribute{id='apiTier', type=STRING}, Attribute{id='subscriptionTier', type=STRING}, Attribute{id='resourceKey', type=STRING}, Attribute{id='resourceTier', type=STRING}, Attribute{id='userId', type=STRING}, Attribute{id='apiContext', type=STRING}, Attribute{id='apiVersion', type=STRING}, Attribute{id='appTenant', type=STRING}, Attribute{id='apiTenant', type=STRING}, Attribute{id='appId', type=STRING}, Attribute{id='apiName', type=STRING}, Attribute{id='propertiesMap', type=STRING}], annotations=[Annotation{name='Import', elements=[Element{key='null', value='org.wso2.throttle.processed.request.stream:1.0.0'}]}]} in execution plan "carbon.super_resource_NewAdvancedThrottlingPolicy_default"`

**Comment by uvindra** [comment]
Closing the issue as it cannot be reproduced with the above patches and following the specified steps
