### ISSUE TITLE
Publisher login problem. Cannot read property "length" from undefined

### ISSUE THREAD

**Issue by grego9** [wso2/carbon-apimgt#8079]
Hi. I am trying to configure an Active-Active deployment as in [here](https://apim.docs.wso2.com/en/next/SetupAndInstall/DeployingWSO2APIManager/SingleNode/configuring-an-active-active-deployment/)

I have already setup two nodes and nginx community as the reverse proxy/balancer.

Both /carbon and /devportal work great, but whenever I try to login on publisher, I got a blank page, and the following error in the log:

`ERROR - WebAppManager org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/publisher/services/login/login_callback.jag#53)
org.jaggeryjs.scriptengine.exceptions.ScriptException: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from undefined (/publisher/services/login/login_callback.jag#53)`

This is my SP callback url for publisher:

`regexp=(https://mywso2cluster.com/publisher/services/auth/callback/login|https://mywso2cluster.com/publisher/services/auth/callback/logout)`

Thank you

**Comment by kalevivek11** [comment]
why it is closed?
