### ISSUE TITLE
[OB] Failure in devportal key generation

### ISSUE THREAD

**Issue by Dinushi** [wso2/carbon-apimgt#9908]
### Description:

An error occurs when generating production keys for a application created in devportal in the OB solution which is based on the API manger 3.1 version.

### Affected Product Version: 
OB-AM 2.0.0

### Environment details (with versions):
- OS:
- Client:
- Env (Docker/K8s):

---

**Comment by chashikajw** [comment]
Closing this issue since the issue is fixed.
